name: Integration Testing

on:
  pull_request:
    branches:
    - 'master'

jobs:
  test-contentful:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test inline images
        id: test_inline_images
        run: |
          . scripts/collect_contentful_images.sh
          CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }} generate_contenful_image_cache_file inline
          wrong_references=$(scripts/test_contentful_image_ids.sh inline || true)
          if [ -n "${wrong_references}" ]
          then
            wrong_references=$(echo "${wrong_references}" | sed 's/$/\\n/g' | tr -d '\n')
            echo "::set-output name=wrong-references::${wrong_references}"
            exit 1
          fi
      - name: Test banner images
        id: test_banner_images
        run: |
          . scripts/collect_contentful_images.sh
          CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }} generate_contenful_image_cache_file banner
          wrong_references=$(scripts/test_contentful_image_ids.sh banner || true)
          if [ -n "${wrong_references}" ]
          then
            wrong_references=$(echo "${wrong_references}" | sed 's/$/\\n/g' | tr -d '\n')
            echo "::set-output name=wrong-references::${wrong_references}"
            exit 1
          fi
      - name: Format Slack message
        id: format_slack_message
        if: failure()
        run: |
          # translate GitHub to Slack user name
          slack_user=$(echo "gabipetrovay" | jq -Rr 'sub("gabipetrovay"; "gabriel") | sub("Stefanvanderlinden"; "stefan") | sub("thekizoch"; "hello")')
          echo "Caused by: ${{ github.actor }} (GitHub) / ${slack_user} (Slack)"

          # prepare the variables we need for the Slack message
          git_run_url="<https://github.com/ivansherbs/insights.ivansherbs.com/actions/runs/${{ github.run_id }}|Integration tests>"
          git_repo_url="<https://github.com/${{ github.repository }}|${{ github.repository }}>"

          echo "${{ steps.test_inline_images.outputs.wrong-references }}"
          echo "${{ steps.test_banner_images.outputs.wrong-references }}"

          formatted_errors=":fire:*The following Contentful image refereces are not valid:*\n\`\`\`${{ steps.test_banner_images.outputs.wrong-references }}\`\`\`"
          slack_message="Nooooo! <@${slack_user}> ${git_run_url} failed when merging into \`master\` of ${git_repo_url}.\n"
          echo "::set-output name=slack-message::${slack_message}${formatted_errors}"
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.1
        id: notify_slack
        if: failure()
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: CR06KUPC1
          slack-optional-icon_emoji: ":fire:"
          slack-text: ${{ steps.format_slack_message.outputs.slack-message }}
      - name: Slack results
        run: |
          echo "Slack status code: $(echo "${SLACK_RESULTS}" | jq -r '.statusCode')"
          echo "Slack status message: $(echo "${SLACK_RESULTS}" | jq -r '.statusMessage')"
          echo "Slack response:"
          echo "${SLACK_RESULTS}" | jq -r '.response'
        env:
          SLACK_RESULTS: ${{ steps.notify_slack.outputs.slack-result }}
        if: failure()
