name: Node.js CI

on:
  pull_request:
    branches:
    - 'master'

jobs:
  test-contentful:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test banner images
        run: |
          . scripts/collect_contentful_images.sh
          CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }} generate_contenful_image_cache_file banner
          scripts/test_contentful_image_ids.sh banner
      - name: Test inline images
        run: |
          . scripts/collect_contentful_images.sh
          CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }} generate_contenful_image_cache_file inline
          scripts/test_contentful_image_ids.sh inline
