name: Node.js CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test content
        id: test_content
        run: |
          # run mocha tests and generate the test report JSON file
          # the test-ci NPM script reads the value of the REPORT_FILE environment variable
          npm run test-ci
          # collect the errors from the test report
          test_errors=$(cat "${REPORT_FILE}" | jq '.tests[] | select(.err.message) | { error: .err.name, title: .fullTitle, message: .err.message }')
          # expose the collected errors as a step output
          error_count=$(echo "${test_errors}" | jq 'length')
          echo "Found ${error_count} errors"
          echo "::set-output name=errors::${test_errors}\n"
          exit "${error_count}"
        env:
          REPORT_FILE: test_report.json
      - name: Notify on error
        if: failure()
        run: |
          echo "The job status was: ${{ job.status }}"
          echo "The test step output was:"
          echo "${{ toJSON(steps.test_content.outputs) }}"
